global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "workout-backend"
    static_configs:
      - targets: ["host.docker.internal:8000"]   # ← ЭТО РАБОТАЕТ ВСЕГДА
    metrics_path: /metrics
    scheme: http